language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t vikram-chauhan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vikram-chauhan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreactaws-env"
  bucker_name: "elasticbeanstalk-ap-south-1-923553532684"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: "$aws_secret_key"
