language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t vikram-chauhan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vikram-chauhan/docker-react npm run test
